#version: '3'
#services:
#  zrx_mesh:
#    image: 0xorg/mesh:latest
#    ports:
#      - "60557:60557/tcp"  # RPC_PORT
#      - "60558:60558/tcp"  # P2P_LISTEN_PORT
#    volumes:
#      - ./.zrx_mesh_data:/usr/mesh/0x_mesh
#    environment:
#      ETHEREUM_CHAIN_ID: 1
#      ETHEREUM_RPC_URL: "ws://host.docker.internal:18536"
#      VERBOSITY: 3

version: '3'

services:
  mesh:
    image: 0xorg/mesh:latest
    restart: always
    volumes:
      - ./.zrx_mesh_data::/usr/mesh/0x_mesh
    ports:
      - '60557:60557'
      - '60558:60558'
      - '60559:60559'
    environment:
      - VERBOSITY=5
      - ETHEREUM_CHAIN_ID=1
      - ENABLE_GRAPHQL_SERVER=true
      - GRAPHQL_SERVER_ADDR=0.0.0.0:60557
        # Set your backing Ethereum JSON RPC endpoint below
        #- ETHEREUM_RPC_URL=ws://172.17.0.1:18536
      - ETHEREUM_RPC_URL=ws://host.docker.internal:18536
      - BLOCK_POLLING_INTERVAL=5s

